name: flutter_3des_plugin
description: Java, android, ios, get the same result by DES encryption and decryption.
version: 2.1.0
homepage: https://github.com/OctMon/flutter_des

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#  plugin:
#    androidPackage: com.example.flutter_3des_plugin
#    pluginClass: Flutter3desPlugin
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_3des_plugin
        pluginClass: Flutter3desPlugin
      ios:
        pluginClass: Flutter3desPlugin
